### ISSUE TITLE
colors get messed up on windows 

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/rustfix#115]
![color](https://user-images.githubusercontent.com/27786/40785290-2428ff72-64b6-11e8-9f43-e7d7bc583cef.png)

now all the white is yellow...

**Comment by killercup** [comment]
might be a dupe of #113

**Comment by killercup** [comment]
@steveklabnik, can you (or someone else on Windows) test that the latest master works now?

**Comment by killercup** [comment]
@steveklabnik ping (or are you still traveling?)

**Comment by steveklabnik** [comment]
Yeah sorry, things have been a bit much.

Master fixes this 🎊

**Comment by killercup** [comment]
Awesome! Published 0.4.1
