### ISSUE TITLE
fix for 2018 doesn't remove unnecessary extern crate statements

### ISSUE THREAD

**Issue by doxxx** [rust-lang-nursery/rustfix#123]
Not sure if this belongs in the preparation fixes or the post-preparation fixes, but `extern crate foo` statements are not removed even though AFAIK they are now superfluous.

**Comment by mati865** [comment]
If you add `+#![warn(rust_2018_idioms)]` rustfix will replace some `extern crate` (but not all of them).

**Comment by doxxx** [comment]
Thanks, I have a lot of warnings now. 👍

**Comment by alexcrichton** [comment]
Indeed @mati865's suggestion should do the trick!
