### ISSUE TITLE
too many errors with edition 2018 and rustfix does not help

### ISSUE THREAD

**Issue by mmrath** [rust-lang-nursery/rustfix#126]
**Repo:** https://github.com/mmrath/fina-server
**Reproduction Step:**

- add `#![feature(rust_2018_preview)]` to model/lib.rs and run cargo build

**Error output**
warning: Working directory dirty
Make sure your working directory is clean so you can easily revert rustfix's changes.
 M model/src/lib.rs
   Compiling cfg-if v0.1.3
   Compiling nodrop v0.1.12
   Compiling scopeguard v0.3.3
   Compiling lazy_static v1.0.1
   Compiling libc v0.2.42
   Compiling memoffset v0.2.1
   Compiling rayon-core v1.4.0
   Compiling either v1.5.0
   Compiling void v1.0.2
   Compiling unicode-xid v0.0.4
   Compiling glob v0.2.11
   Compiling ucd-util v0.1.1
   Compiling quote v0.3.15
   Compiling regex v1.0.0
   Compiling unicode-xid v0.1.0
   Compiling num-traits v0.2.4
   Compiling unicode-width v0.1.5
   Compiling utf8-ranges v1.0.0
   Compiling quick-error v1.2.2
   Compiling regex v0.2.11
   Compiling vec_map v0.8.1
   Compiling ansi_term v0.11.0
   Compiling num-integer v0.1.38
   Compiling strsim v0.7.0
   Compiling rustc-demangle v0.1.8
   Compiling bindgen v0.37.0
   Compiling termcolor v0.3.6
   Compiling serde v1.0.66
   Compiling bitflags v1.0.3
   Compiling pq-sys v0.4.5
   Compiling remove_dir_all v0.5.1
   Compiling peeking_take_while v0.1.2
   Compiling yansi v0.4.0
   Compiling version_check v0.1.3
    Checking matches v0.1.6
    Checking unicode-normalization v0.1.7
    Checking antidote v1.0.0
    Checking futures v0.1.21
    Checking untrusted v0.6.2
    Checking byteorder v1.2.3
    Checking percent-encoding v1.0.1
    Checking rand_core v0.2.1
    Checking safemem v0.2.0
    Checking language-tags v0.2.2
    Checking traitobject v0.1.0
    Checking httparse v1.2.4
    Checking typeable v0.1.2
    Checking indexmap v1.0.1
    Checking smallvec v0.6.2
    Checking dtoa v0.4.2
    Checking itoa v0.4.1
    Checking state v0.4.1
   Compiling crossbeam-utils v0.2.2
   Compiling log v0.4.2
   Compiling arrayvec v0.4.7
   Compiling unreachable v1.0.0
   Compiling synom v0.11.3
   Compiling proc-macro2 v0.3.5
   Compiling proc-macro2 v0.4.6
   Compiling regex-syntax v0.6.1
   Compiling regex-syntax v0.5.6
   Compiling textwrap v0.9.0
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling memchr v2.0.1
   Compiling memchr v1.0.2
   Compiling atty v0.2.10
   Compiling which v1.0.5
   Compiling time v0.1.40
   Compiling humantime v1.1.1
   Compiling clang-sys v0.22.0
   Compiling backtrace v0.3.8
    Checking unicode-bidi v0.3.4
   Compiling unicase v1.4.2
    Checking scheduled-thread-pool v0.2.0
    Checking isatty v0.1.8
   Compiling pear_codegen v0.1.0 (http://github.com/SergioBenitez/Pear?rev=54667ae#54667aef)
   Compiling rocket v0.4.0-dev (https://github.com/SergioBenitez/Rocket#7b4b0646)
   Compiling rocket_codegen v0.4.0-dev (https://github.com/SergioBenitez/Rocket#7b4b0646)
    Checking rand v0.5.2
    Checking base64 v0.6.0
    Checking base64 v0.9.2
   Compiling thread_local v0.3.5
   Compiling log v0.3.9
   Compiling syn v0.11.11
   Compiling crossbeam-epoch v0.3.1
   Compiling quote v0.5.2
   Compiling quote v0.6.3
   Compiling rand v0.3.22
   Compiling tempdir v0.3.7
   Compiling clap v2.31.2
   Compiling aho-corasick v0.6.4
   Compiling nom v3.2.1
    Checking r2d2 v0.8.2
    Checking nom v4.0.0
    Checking futures-cpupool v0.1.8
    Checking uuid v0.6.5
   Compiling mime v0.2.6
   Compiling syn v0.13.11
   Compiling crossbeam-deque v0.2.0
   Compiling syn v0.14.2
   Compiling synstructure v0.6.1
   Compiling cexpr v0.2.3
    Checking toml v0.4.6
    Checking serde_json v1.0.21
    Checking chrono v0.4.3
   Compiling env_logger v0.5.10
   Compiling diesel_derives v1.3.0
   Compiling failure_derive v0.1.1
   Compiling rayon v1.0.1
    Checking idna v0.1.4
   Compiling serde_derive v1.0.66
   Compiling rocket_codegen_next v0.4.0-dev (https://github.com/SergioBenitez/Rocket#7b4b0646)
    Checking url v1.7.0
   Compiling failure v0.1.1
    Checking hyper v0.10.13
   Compiling cc v1.0.17
    Checking pear v0.1.0 (http://github.com/SergioBenitez/Pear?rev=54667ae#54667aef)
    Checking diesel v1.3.2
   Compiling libloading v0.5.0
   Compiling ring v0.13.0-alpha5
    Checking cookie v0.11.0-dev (https://github.com/alexcrichton/cookie-rs?rev=0365a18#0365a18e)
    Checking rocket_http v0.4.0-dev (https://github.com/SergioBenitez/Rocket#7b4b0646)
    Checking rocket_contrib v0.4.0-dev (https://github.com/SergioBenitez/Rocket#7b4b0646)
   Compiling argonautica v0.1.4
    Checking r2d2-diesel v1.0.0
    Checking fina-schema v0.1.0 (file:///Users/mmrath/Projects/Rust/billac/fina-server/schema)
    Checking fina-util v0.1.0 (file:///Users/mmrath/Projects/Rust/billac/fina-server/util)
    Checking fina-model v0.1.0 (file:///Users/mmrath/Projects/Rust/billac/fina-server/model)
error[E0432]: unresolved import `super::User`=====================>  ] 212/216: fina-model
 --> model/src/core/onetime_token.rs:3:5
  |
3 | use super::User;
  |     ^^^^^^^^^^^ no `User` in `core`. Did you mean to use `user`?

error[E0432]: unresolved import `core::User`
 --> model/src/core/user_password.rs:3:5
  |
3 | use core::User;
  |     ^^^^^^^^^^ no `User` in `core`. Did you mean to use `user`?

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/common.rs:60:3
   |
60 | #[table_name = "currency"]
   |   ^^^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/common.rs:50:3
   |
50 | #[table_name = "country"]
   |   ^^^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/common.rs:42:3
   |
42 | #[table_name = "language"]
   |   ^^^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/common.rs:33:3
   |
33 | #[table_name = "timezone"]
   |   ^^^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/common.rs:25:3
   |
25 | #[table_name = "datetime_format"]
   |   ^^^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
 --> model/src/core/common.rs:7:3
  |
7 | #[table_name = "date_format"]
  |   ^^^^^^^^^^

error: cannot find attribute macro `sql_type` in this scope
  --> model/src/core/onetime_token.rs:41:3
   |
41 | #[sql_type = "SqlTokenType"]
   |   ^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/onetime_token.rs:20:3
   |
20 | #[table_name = "onetime_token"]
   |   ^^^^^^^^^^

error[E0433]: failed to resolve. Use of undeclared type or module `TokenType`
  --> model/src/core/onetime_token.rs:50:13
   |
50 |             TokenType::UserActivation => out.write_all(b"UserActivation")?,
   |             ^^^^^^^^^ Use of undeclared type or module `TokenType`

error[E0433]: failed to resolve. Use of undeclared type or module `TokenType`
  --> model/src/core/onetime_token.rs:51:13
   |
51 |             TokenType::PasswordReset => out.write_all(b"PasswordReset")?,
   |             ^^^^^^^^^ Use of undeclared type or module `TokenType`

error[E0433]: failed to resolve. Use of undeclared type or module `TokenType`
  --> model/src/core/onetime_token.rs:60:40
   |
60 |             b"AccountActivation" => Ok(TokenType::UserActivation),
   |                                        ^^^^^^^^^ Use of undeclared type or module `TokenType`

error[E0433]: failed to resolve. Use of undeclared type or module `TokenType`
  --> model/src/core/onetime_token.rs:61:36
   |
61 |             b"PasswordReset" => Ok(TokenType::PasswordReset),
   |                                    ^^^^^^^^^ Use of undeclared type or module `TokenType`

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/user.rs:12:3
   |
12 | #[table_name = "app_user"]
   |   ^^^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/user_password.rs:25:3
   |
25 | #[table_name = "user_password"]
   |   ^^^^^^^^^^

error: cannot find attribute macro `table_name` in this scope
  --> model/src/core/user_password.rs:13:3
   |
13 | #[table_name = "user_password"]
   |   ^^^^^^^^^^

error[E0412]: cannot find type `DateFormat` in this scope
  --> model/src/core/common.rs:15:6
   |
15 | impl DateFormat {
   |      ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `DateFormat` in this scope
  --> model/src/core/common.rs:16:56
   |
16 |     pub fn find_all(conn: &DbConnection) -> Result<Vec<DateFormat>, Error> {
   |                                                        ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `TokenType` in this scope
  --> model/src/core/onetime_token.rs:35:21
   |
35 |     pub token_type: TokenType,
   |                     ^^^^^^^^^ did you mean `SqlTokenType`?

error[E0412]: cannot find type `TokenType` in this scope
  --> model/src/core/onetime_token.rs:31:10
   |
31 | #[derive(Insertable, Debug, Serialize, Deserialize, Clone)]
   |          ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `TokenType` in this scope
  --> model/src/core/onetime_token.rs:47:34
   |
47 | impl ToSql<SqlTokenType, Pg> for TokenType {
   |                                  ^^^^^^^^^ did you mean `SqlTokenType`?

error[E0412]: cannot find type `TokenType` in this scope
  --> model/src/core/onetime_token.rs:57:36
   |
57 | impl FromSql<SqlTokenType, Pg> for TokenType {
   |                                    ^^^^^^^^^ did you mean `SqlTokenType`?

error[E0412]: cannot find type `OnetimeToken` in this scope
  --> model/src/core/onetime_token.rs:67:6
   |
67 | impl OnetimeToken {
   |      ^^^^^^^^^^^^ did you mean `NewOnetimeToken`?

error[E0412]: cannot find type `OnetimeToken` in this scope
  --> model/src/core/onetime_token.rs:71:24
   |
71 |     ) -> Result<Option<OnetimeToken>, Error> {
   |                        ^^^^^^^^^^^^ did you mean `NewOnetimeToken`?

error[E0412]: cannot find type `OnetimeToken` in this scope
  --> model/src/core/onetime_token.rs:84:25
   |
84 |     ) -> Result<Option<(OnetimeToken, User)>, Error> {
   |                         ^^^^^^^^^^^^ did you mean `NewOnetimeToken`?

error[E0412]: cannot find type `OnetimeToken` in this scope
  --> model/src/core/onetime_token.rs:92:23
   |
92 |             .first::<(OnetimeToken, User)>(conn)
   |                       ^^^^^^^^^^^^ did you mean `NewOnetimeToken`?

error[E0412]: cannot find type `User` in this scope
  --> model/src/core/user.rs:51:6
   |
51 | impl User {
   |      ^^^^ not found in this scope

error[E0412]: cannot find type `User` in this scope
  --> model/src/core/user.rs:52:70
   |
52 |     pub fn insert(conn: &DbConnection, new_user: &NewUser) -> Result<User, Error> {
   |                                                                      ^^^^ not found in this scope

error[E0412]: cannot find type `User` in this scope
  --> model/src/core/user.rs:59:49
   |
59 |     pub fn activate(conn: &DbConnection, user: &User) -> Result<(), Error> {
   |                                                 ^^^^ not found in this scope

error[E0412]: cannot find type `User` in this scope
  --> model/src/core/user.rs:73:47
   |
73 |     pub fn update(conn: &DbConnection, user: &User) -> Result<User, Error> {
   |                                               ^^^^ not found in this scope

error[E0412]: cannot find type `User` in this scope
  --> model/src/core/user.rs:73:63
   |
73 |     pub fn update(conn: &DbConnection, user: &User) -> Result<User, Error> {
   |                                                               ^^^^ not found in this scope

error[E0412]: cannot find type `User` in this scope
  --> model/src/core/user.rs:80:64
   |
80 |     pub fn find(conn: &DbConnection, id: i64) -> Result<Option<User>, Error> {
   |                                                                ^^^^ not found in this scope

error[E0412]: cannot find type `User` in this scope
  --> model/src/core/user.rs:99:83
   |
99 |     pub fn find_by_username(conn: &DbConnection, username: &str) -> Result<Option<User>, Error> {
   |                                                                                   ^^^^ not found in this scope

error[E0412]: cannot find type `User` in this scope
   --> model/src/core/user.rs:105:22
    |
105 |             .first::<User>(conn)
    |                      ^^^^ not found in this scope

error[E0412]: cannot find type `UserPassword` in this scope
  --> model/src/core/user_password.rs:32:6
   |
32 | impl UserPassword {
   |      ^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `UserPassword` in this scope
  --> model/src/core/user_password.rs:33:62
   |
33 |     pub fn find(conn: &DbConnection, user_id: i64) -> Result<UserPassword, Error> {
   |                                                              ^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `NewUserPassword` in this scope
  --> model/src/core/user_password.rs:41:55
   |
41 |     pub fn insert(conn: &DbConnection, new_password: &NewUserPassword) -> Result<(), Error> {
   |                                                       ^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 38 previous errors

Some errors occurred: E0412, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: Could not compile `fina-model`.

To learn more, run the command again with --verbose.

**Comment by alexcrichton** [comment]
Thanks for the report! I've moved this upstream to https://github.com/rust-lang/rust/issues/52219 with a minimized test case
