### ISSUE TITLE
`--allow-staged` flag

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang-nursery/rustfix#127]
As a generalization of `--allow-dirty`, there could be an `--allow-staged` flag that lets us run only if there are no unstaged changes in Git (and similarly if Mercurial, Pijul, or Fossil have an analogue of Git's staging area—I'm not familiar), the rationale being that content that has been `git add`ed isn't actually in danger of being permanently eaten by a poor suggestion application, because you can `git checkout -- .` to back out the changes.

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/cargo/issues/5737 now that `cargo fix` has changed homes
