### ISSUE TITLE
Diff-like output

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rustfix#13]
While it's nice to read something like

``` plain
Suggestion - Replace:

    mem::transmute::<*mut c_void,
                     &mut Box<FnMut(&MenuItem, &Window)>>(data)(&menu_item, &window);

with:

    &mut *(data as *mut Box<for<'r, 'r> std::ops::FnMut(&'r menus::MenuItem, &'r windows::Window)>)
```

it might be more useful to have a bit of context and see exactly what is getting replaced. A diff-view (with character-precision highlighting, not just lines) should work nicely.

This could also be an optional CLI flag, though it might be better to just keep rustfix as simple (and non-configurable) as possible for now.

This might be as easy as adjusting the "apply replacement" function to not always save the output and run [print_diff](http://johannh.me/difference.rs/difference/fn.print_diff.html) over a slice of `max(0, start.line - context)...min(file.lines().count(), end.line + context`.

**Comment by mcarton** [comment]
> This could also be an optional CLI flag

IMO it should be the default.
By default show ±2 lines of context and change the prompt to:

```
What do you want to do? [r]eplace | show more [c]ontext | [s]kip | save and [q]uit | [a]bort (without saving)
```
Pressing `c` would add 2 more lines of context (or maybe the whole block?) and could be pressed as much as the user wants.

**Comment by killercup** [comment]
Sounds good. How easy is it to find a block in rust code? Just going up/down to the first line that is indented one indent-level less might be viable.
