### ISSUE TITLE
Clippy integration is undocumented

### ISSUE THREAD

**Issue by kornelski** [rust-lang-nursery/rustfix#130]
Clippy is mentioned in the README, but the README contains no information on *how* to use cargo-fix and clippy together.

`cargo fix --help` does not contain information about Clippy integration either.

In the Clippy's README and help there is nothing about rustfix either.

**Comment by Manishearth** [comment]
I think right now the focus is for this to be used for editions, and post-edition worry about clippy (the integration then will be different too, since clippy is changing a bunch)

**Comment by estk** [comment]
@Manishearth, totally understandable. However it isn't clear if this works with Clippy or not. At the least it would be helpful to know that it does not. I'd be happy to update the docs if you could provide an outline here of what the status is.

**Comment by Manishearth** [comment]
It _does_ work with clippy, it's just not polished right now. It's a complicated answer -- you can get it to work with clippy, but it won't work well, and it's not how it will eventually work.

**Comment by CoolOppo** [comment]
How do you try it with clippy?

**Comment by luciusmagn** [comment]
there's a clippy integration? Neat! How do I try it?

**Comment by Manishearth** [comment]
You're not supposed to use it yet. We're working on properly exposing it, it's a part of https://github.com/rust-lang/rust-clippy/issues/3837

**Comment by luciusmagn** [comment]
Alrighty :smile: thanks a lot for the lightning fast response! Is there anything I can do to help?

**Comment by Manishearth** [comment]
Not at the moment, this is mostly blocked on review from cargo.
