### ISSUE TITLE
cargo fix does not support cargo features

### ISSUE THREAD

**Issue by withoutboats** [rust-lang-nursery/rustfix#136]
I'm not sure if there's another way to do this, but I don't know how to run `cargo fix` with different features turned on, so that it will be run on the `cfg`'d code for that feature.

I expected `cargo fix --all-features` or `cargo fix --feature X` to work

**Comment by alexcrichton** [comment]
Indeed! The `cargo fix` that existed in this repo doesn't support cargo features but the version merged upstream into Cargo does. Just waiting on a nightly release now!

**Comment by withoutboats** [comment]
Awesome!
