### ISSUE TITLE
Attributes applied to deleted items should also be deleted.

### ISSUE THREAD

**Issue by jrobsonchase** [rust-lang-nursery/rustfix#147]
For example, if I have 

```rust
#[cfg(unix)]
extern crate nix;

mod foo;
```

and then run `cargo fix --edition-idioms`, currently only the `extern crate nix;` line gets deleted, which makes the `#[cfg(unix)]` attribute apply to `mod foo;`, which is not what was intended.

I'm currently using cargo-fix v0.4.1  from crates.io.

**Comment by Manishearth** [comment]
Could you file this issue on the rust repo itself? rustfix dumbly applies
suggestions from the compiler


That said, it might be worth catching this specific case in rustfix itself
since due to the way the compiler works it might be tricky to generate this
suggestion

**Comment by killercup** [comment]
Wow, looks like a good catch!

That's actually a bug with the rust compiler, which outputs the diagnostic info, though. Can you open an issue at <https://github.com/rust-lang/rust/issues>? Otherwise I can do it.

**Comment by killercup** [comment]
@Manishearth y u so quick

Also, neither rustfix nor cargo-fix (which lives in the cargo repo) has no knowledge of the source code's semantics. cargo-fix will try to pass cfgs, though…

**Comment by jrobsonchase** [comment]
@killercup @Manishearth Sure thing! :+1:

**Comment by killercup** [comment]
@jrobsonchase thanks so much for reporting this… _twice_! Closing this issue here in favor of <https://github.com/rust-lang/rust/issues/54400>.
