### ISSUE TITLE
Use fancy interactive select in CLI

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rustfix#15]
While entering letters to step through suggestions is fun, it might be cooler to have an interactive select box.

The node module [inquirer](https://www.npmjs.com/package/inquirer) does some cool stuff in that regard, e.g.

![](https://dl.dropboxusercontent.com/u/59696254/inquirer/list-prompt.png)

or

![](https://dl.dropboxusercontent.com/u/59696254/inquirer/expand-prompt-2.png)

I think this is a great opportunity to create a new crate. The closest thing I could find in rust (without going all the way to curses-rs) is [this snippet](https://github.com/yagince/gitx-rs/blob/b6626d9fab3ba5a70e2d63d8df25d46654987f18/src/git_cb_main.rs#L56) which uses termbox-bindings. [termion](https://github.com/ticki/termion), a pure-rust termbox clone, might also be interesting.

**Comment by mcarton** [comment]
The first one looks like it only works with arrows. That's not so great IMO. I'd prefer to only have to type one of “rsq” without the need for Enter.

**Comment by killercup** [comment]
Yeah, I'd like to have both options (select with up/down, then enter; or
press one of rscaq) as well.

Personally I also hope we can get to a point where it makes sense to always
press enter to accept the preselected "replace", though 😄
Martin Carton <notifications@github.com> schrieb am Mo. 11. Juli 2016 um
16:44:

**Comment by mcarton** [comment]
> Personally I also hope we can get to a point where it makes sense to always press enter to accept the preselected "replace", though :smile:

I'm not so sure this would be possible. For some lints the suggestion could be applied as is, 99.9% of the cases. But for some lints, the suggestion really is just a suggestion.

**Comment by killercup** [comment]
Ha, let me propose an `--do-your-best` options, then: Apply one
suggestions, run `cargo test`, keep it if the tests still work, reject it
otherwise. Repeat for all suggestions. Tag line: "Run this over lunch and
impress your boss!" 😉


Martin Carton <notifications@github.com> schrieb am Mo. 11. Juli 2016 um
16:56:

**Comment by Munksgaard** [comment]
I started working on a prototype for this. I'll see if I can get it up on github sometime within this week.
