### ISSUE TITLE
feature-request: all changes printed to a "fix-log"

### ISSUE THREAD

**Issue by xetra11** [rust-lang-nursery/rustfix#19]
Hey!

just curious if you plan to create some kind of, I call it "fixlog", where every replace-to hunk will be logged. I don't know the real use for this yet but I'd like to see what I changed or better said what rustfix suggested. Maybe as a learning/best practice resource afterwards?

greets
Charlie

**Comment by killercup** [comment]
Interesting idea. So far, I've been using `git diff` to see what rustfix actually changed. Where would those fixlog entries live? My first guess would be to expand Clippy's lint docs with more examples (maybe ones that rustfix generated).

**Comment by xetra11** [comment]
I did not used Clippy yet and therefore cannot tell anything about how good the lint docs might fit to this. Well in my little imagination I see a glowing folder containing fix-logs to be ready to discovered in the doc folder of the rust lib/binary project.

**Comment by killercup** [comment]
> not used Clippy yet

Charlie, you've been missing out on so much awesomeness! 😮 You should `rustup update; rustup override nightly; cargo install clippy; cargo clippy` in your project's directory _right now!_

BTW, I recently made the clippy docs a bit more accessible: https://manishearth.github.io/rust-clippy/current/

Rustfix is pretty experimental right now. If you learn anything from it (or clippy), it'd be awesome if you could send PRs to improve clippy's docs. Currently the examples mostly just contain examples for code that will trigger the lint (i.e., bad code) but now examples on how to fix it. (Well, that's just my suggestion; I'm just guessing that the clippy authors would like that as well.)

**Comment by xetra11** [comment]
I'm onto clippy world right now! Maybe it helps with my lifetime issues ;)
