### ISSUE TITLE
Make binary deps optional

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rustfix#27]
I think cargo allows us to 

```toml
[[bin]]
name = "rustfix"
features = ["cli"]
```

**Comment by oli-obk** [comment]
If you depend on a crate, won't the binaries get ignored anyway?

**Comment by killercup** [comment]
Sure, but if someone depends on rustfix right now, they'll have to compile clap, which is only used in the binary. That's what I aim to avoid with this.

**Comment by killercup** [comment]
solved by splitting into two crates
