### ISSUE TITLE
Apply only certain fixes

### ISSUE THREAD

**Issue by Dushistov** [rust-lang-nursery/rustfix#36]
I can not find any docs about functionality `applying only certain fixes`,
so here is feature request: it would be nice to filter possible fixes and applying only some classes of them.

For example, during development phase you can have bunch of warning `unused something`,
this is ok on development stage, but should be fixed on stabializing feature stage.

Also, for example I read about `rustfix` [here](https://www.reddit.com/r/rust/comments/6lwc9n/how_you_write_code_on_rust/?ref=share&ref_source=link) and would like to try to fix `use` issues, but only for them.

So, it would be great to have something like `--ignore-class=unused` and `--apply-only-for-class=use` command line arguments.

**Comment by killercup** [comment]
Yes, whitelisting is certainly something we should add to ensure that casual users only ever get suggestions that work! I think it'd be good to hard-code some known-good-lints and only apply these unless the user sets `--experimental`. This will also make `--yolo` more stable. (I've previously talked with The Clippy Gang and the Dev Tools Team about this.)

Would you like to work on? I think a good first PR would add the whitelist and then `.filter` suggestions the suggestions [here](https://github.com/killercup/rustfix/blob/de04a050fe73f7d6001acc9364ff24d5eb6b9ce2/src/main.rs#L82).

**Comment by shepmaster** [comment]
I want to +1 the ability to only automatically fix a single specific lint at a time.

> whitelisting is certainly something we should add to ensure that casual users only ever get suggestions that work

I read the original comment as something different. Your comment seems to be focused on "safe" vs "scary" fixes. That's also sounds useful, but I don't think it's this issue.

----

My preferred workflow when introducing new lints to an existing code base is:

1. Install the tool.
1. Have the tool generate a "TODO" file that marks all existing lint violations as ignored.
  - Ideally this file is split into two dimensions: file and lint type.

At this point, I commit and push this progress. This prevents any files from getting worse. Then, the team cycles on the following steps:

1. Pick a single lint that is being ignored.
1. Fix all of or a subset of the files for that one lint, and push it.

What's interesting to note is that this entire process usually repeats *when a new version of the linting tool is released*, as this often introduces new lints that we have been unknowingly violating.

When something is automatic, I want to fix it, then manually perform a `cargo test` and a `git diff` to review it myself. This `--only=use` option would allow that.

This is strongly influenced by [RuboCop](https://github.com/bbatsov/rubocop).

**Comment by killercup** [comment]
@shepmaster sorry if my last comment was confusing! I was thinking about the implementation of the whitelist, and that we can use its default value to show which lint suggestions we consider to be stable.

Also: Thanks for reminding me to look to get #37 merged :)

**Comment by shepmaster** [comment]
> I was thinking about the implementation of the whitelist

Ok, and it sounds like that's something else besides this issue (which sounds correct to me). Is there a link to the issue for the whitelist you are thinking about?

**Comment by killercup** [comment]
I'm not sure there is one, probably just some comments on the PR. I've been slacking maintaining rustfix for a while and should probably write up some plans. Feel free to open new issues for every weird thing you encounter in the meantime :)

**Comment by killercup** [comment]
FYI https://github.com/rust-lang/rust/pull/45484 just landed which makes identifying lint names in diagnostic output way easier
