### ISSUE TITLE
Fixing unused imports

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang-nursery/rustfix#56]
I really like `rustfix` and expectations are more :)

`cargo build` identifies unused imports. I would like to see `rustfix` provides similar suggestion and remove these unused imports.

e.g.

```
warning: unused import: `std::io::prelude::*`
  --> src/tiso/tiso_msg.rs:10:5
   |
10 | use std::io::prelude::*;
   |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `std::fmt`
  --> src/tiso/tiso_msg.rs:13:5
   |
13 | use std::fmt;
   |     ^^^^^^^^
```

**Comment by oli-obk** [comment]
This should be fixed in rustc by creating an empty suggestion

**Comment by killercup** [comment]
Yeah, I've been missing that too! :)

The strategy is to suggest replacing the unused import with an empty string. If it is the only item in the `use` (i.e., `std::fs` in `use std::fs;` is unused, in contrast to `File` in `use std::fs::{File, copy}` is unused), remove the whole `use` statement.

This suggestion needs to be implemented in rustc, probably [here](https://github.com/rust-lang/rust/blob/70517540dad71801a2ab903fb91d3e0c7406f115/src/librustc_typeck/check_unused.rs#L27-L46).

I couldn't find an open issue there, you should open one! Feel free to copy this comment too if you like :) (Maybe mention https://github.com/rust-lang/rust/issues/42823 as it tracks a few diagnostic things already.)

**Comment by rohitjoshi** [comment]
It would be good to remove unused crates `extern crate xxx`
