### ISSUE TITLE
Rustfix does not work when using a workspace

### ISSUE THREAD

**Issue by Lapz** [rust-lang-nursery/rustfix#59]
[![asciicast](https://asciinema.org/a/X8eLGfBveD2W481RixswGwnfB.png)](https://asciinema.org/a/X8eLGfBveD2W481RixswGwnfB)

When using rustfix in a workspaced project it fails to apply the correct fixes and gives an IO error.

**Comment by killercup** [comment]
Rustup is not currently aware of workspaces at all. We should make sure it does something useful, and then probably also add some features to let users decide which workspace member to run it on.

**Comment by alexcrichton** [comment]
I think this was fixed in https://github.com/rust-lang-nursery/rustfix/pull/66, so closing
