### ISSUE TITLE
rustfix run from the `src` directory fails

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustfix#61]
I was working on a cargo project and I ran rustfix from the `src` directory. This seemed to be working but ended with:

```
An error occured: I/O error
Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
Cause: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Running from alongside the `Cargo.toml` worked fine.

**Comment by nikomatsakis** [comment]
cc @Manishearth

**Comment by Manishearth** [comment]
cc @mgattozzi

**Comment by mgattozzi** [comment]
@Manishearth is this part of the integration stuff for the epoch stuff you need help wtih?

**Comment by Manishearth** [comment]
Yeah!

**Comment by killercup** [comment]
Wait is this the same thing I wanted to fix for clippy where we should use
CARGO_PKG_ROOT (or similar) instead of cwd?

Manish Goregaokar <notifications@github.com> schrieb am Di. 27. März 2018
um 17:20:

**Comment by alexcrichton** [comment]
I believe this should be fixed now that `cargo fix` has been rewritten
