### ISSUE TITLE
Warn if a VCS isn't detected

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfix#75]
If we don't manage to find anything like Git/Mercurial/SVN then we should display a warning in one way or another and maybe even wait for the user to confirm before proceeding. Automatically changing code without version control is a scary prospect!

**Comment by BrainMaestro** [comment]
Hi, I'd like to work on this. I'm guessing all the related code for this will go into the binary?

**Comment by killercup** [comment]
Hi @BrainMaestro, cool!

I'd probably add something right below [this](https://github.com/rust-lang-nursery/rustfix/blob/df678eb907e84d0ae6897542432f5dc4ba3ea461/cargo-fix/src/cli.rs#L51-L53) where you bail out unless a VCS was detected or an override flag was given. The code for detecting a VCS is probably not that large and can just be another function in that file. Have a look at the source code for [cargo-new](https://github.com/rust-lang/cargo/blob/b24b455c327048df940ab8322cc6f9d361fef918/src/cargo/ops/cargo_new.rs) which should contain something like this already.
