### ISSUE TITLE
In autofix mode, skip suggestions with multiple options

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rustfix#78]
Some lints yield multiple valid suggestions, e.g., [here](https://play.rust-lang.org/?gist=56fa4bbfa29fc67f9ab7d4282b0ac6d9&version=stable&mode=debug)

```rust
fn main() {
    let xs = vec![String::from("foo")];
    let d: &Display = &xs;
    println!("{}", d);
}
```

We should not try to apply suggestions with more than one option and instead just skip them.

**Comment by jrlusby** [comment]
I'd like to handle this issue.

What do you mean by in autofix mode? I'm trying to figure out what part of the process would be best for essentially dropping the multi option suggestions. get_suggesstions_from_json in lib.rs seems like a good place but I don't see how that would relate to autofix mode, if I put it there it would pretty much just always ignore multi option suggestions unless I add an argument to select a specific option or something.

**Comment by killercup** [comment]
@jrlusby awesome!

Currently, all rustfix has in "autofix mode". But previous versions of it were interactive – you'd get prompted for each (fixable) error, and presented with 1 or more fix to choose from. (I'm not particularly inclined to re-add that, editor plugins powered by RLS are probably more user friendly.)

Have a look at `collect_suggestions`: This is where we go from `Diagnostic` (rustc-defined) to `Suggestion` (rustfix-defined). (Right now, `Suggestion`'s `solutions` field is a vector, but IIRC this is because one fix can require multiple edits.) It should be possible to determine in this function if we are dealing with a warning that has multiple possible fixes. (At a later date we can make this optional if we want to go back to the interactive mode.)

We should probably collect some sample of rustc's output for lints with multiple fixes. IIRC, if you forget to add a `use foo` where the foo is somewhat ambiguous (like, `Display` which is either from std::fmt or std::path), you get this.
