### ISSUE TITLE
Figure out how to force `cargo fix` to run

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfix#79]
Currently if you run `cargo +nightly check` and then `cargo +nightly fix` it won't actually do anything because Cargo will think it's cached. Somehow we should convince Cargo that it should at least rerun itself for the workspace-related crates.

**Comment by killercup** [comment]
There is also a long-standing clippy issue about this IIRC

**Comment by phansch** [comment]
The clippy issue is this one, I believe: https://github.com/rust-lang-nursery/rust-clippy/issues/2604

**Comment by killercup** [comment]
btw i'm totally fine with executing `touch <some-file>` as a first work-around here!

**Comment by killercup** [comment]
(I have a WIP for this but waited for rustfix to land in cargo; will open a PR there in a bit)

**Comment by alexcrichton** [comment]
Migrated to https://github.com/rust-lang/cargo/issues/5736
