### ISSUE TITLE
Should rustfix fix broken code?

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfix#80]
Should `cargo fix` keep going if the first `cargo check` fails? That is, if we're looking at broken code, should `cargo fix` attempt to keep going and fixing code?

In situations like this we can't actually detect if our changes caused further breakage, so we'd run the risk of making the situation *worse* by adding more errors.

**Comment by killercup** [comment]
Hm, I wouldn't do that. I'd treat suggestions on non-compiling code as undefined behavior, tbh.

Other people might disagree however. An edge case might be `#[deny(warnings)]`

**Comment by alexcrichton** [comment]
Ok this sounds reasonable, and I think we can work around `#![deny(warnings)]` with judicious application of `--cap-lints`
