### ISSUE TITLE
Trials & Errors

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rustfix#9]
Let's collect some problems with rustfix encountered in real life here.

**Comment by killercup** [comment]
Just a few to get started: https://gist.github.com/killercup/7142b37c1dbd1e5266fc9b0c2ee3ebb8

As this might also interest the good folks who did all the work (i.e., wrote the clippy lints), I'll start with: cc @mcarton

**Comment by mcarton** [comment]
I'll look into it, but is [the one about `new_without_default`](https://gist.github.com/killercup/7142b37c1dbd1e5266fc9b0c2ee3ebb8#probably-creating-syntax-errors) still broken? It should be fixed in 0.0.79.

**Comment by killercup** [comment]
Yup, I installed the new version before testing. Let me make a diff and open a new issue.

**Comment by mcarton** [comment]
By the way the problem you describe with `needless_range_loop` is actually the feature I described in https://github.com/killercup/rustfix/issues/14#issuecomment-231754724.
